from __future__ import annotations

from typing import Any


DEFAULT_TRACKED_ACCOUNTS: list[dict[str, Any]] = [
    {
        "platform": "youtube",
        "display_name": "BabyBus",
        "handle": "@BabyBus",
        "homepage_url": "https://www.youtube.com/@BabyBus",
        "query_hint": "BabyBus nursery rhymes latest",
        "category": "children_content",
    },
    {
        "platform": "youtube",
        "display_name": "Bebefinn",
        "handle": "@Bebefinn",
        "homepage_url": "https://www.youtube.com/@Bebefinn",
        "query_hint": "Bebefinn nursery rhymes latest",
        "category": "children_content",
    },
    {
        "platform": "youtube",
        "display_name": "Pinkfong",
        "handle": "@Pinkfong",
        "homepage_url": "https://www.youtube.com/@Pinkfong",
        "query_hint": "Pinkfong latest songs animation",
        "category": "children_content",
    },
    {
        "platform": "youtube",
        "display_name": "Babyshark",
        "handle": "@BabyShark",
        "homepage_url": "https://www.youtube.com/@BabyShark",
        "query_hint": "Baby Shark official latest songs",
        "category": "children_content",
    },
    {
        "platform": "youtube",
        "display_name": "Doko Demo Jamboree",
        "handle": "@DokoDemoJamboree",
        "homepage_url": "https://www.youtube.com/@DokoDemoJamboree",
        "query_hint": "Doko Demo Jamboree latest",
        "category": "children_content",
    },
    {
        "platform": "youtube",
        "display_name": "Super Simple Songs",
        "handle": "@SuperSimpleSongs",
        "homepage_url": "https://www.youtube.com/@SuperSimpleSongs",
        "query_hint": "Super Simple Songs latest",
        "category": "children_content",
    },
    {
        "platform": "youtube",
        "display_name": "贝乐虎",
        "handle": "@Beilehu",
        "homepage_url": "https://www.youtube.com/@Beilehu",
        "query_hint": "贝乐虎 儿歌 latest",
        "category": "children_content",
    },
    {
        "platform": "youtube",
        "display_name": "Doggyland",
        "handle": "@DoggylandKidsSongs",
        "homepage_url": "https://www.youtube.com/@DoggylandKidsSongs",
        "query_hint": "Doggyland Kids Songs latest",
        "category": "children_content",
    },
    {
        "platform": "tiktok",
        "display_name": "Pinkfong",
        "handle": "@pinkfong_official",
        "homepage_url": "https://www.tiktok.com/@pinkfong_official",
        "query_hint": "site:tiktok.com/@pinkfong_official Pinkfong",
        "category": "children_content",
    },
    {
        "platform": "tiktok",
        "display_name": "Babyshark",
        "handle": "@babyshark_brooklyn",
        "homepage_url": "https://www.tiktok.com/@babyshark_brooklyn",
        "query_hint": "site:tiktok.com/@babyshark_brooklyn Babyshark",
        "category": "children_content",
    },
    {
        "platform": "tiktok",
        "display_name": "Doko Demo Jamboree",
        "handle": "@dokojam",
        "homepage_url": "https://www.tiktok.com/@dokojam",
        "query_hint": "site:tiktok.com/@dokojam Doko Demo Jamboree",
        "category": "children_content",
    },
    {
        "platform": "tiktok",
        "display_name": "Super Simple Songs",
        "handle": "@supersimpleofficial",
        "homepage_url": "https://www.tiktok.com/@supersimpleofficial",
        "query_hint": "site:tiktok.com/@supersimpleofficial Super Simple Songs",
        "category": "children_content",
    },
    {
        "platform": "douyin",
        "display_name": "周鸿祎（红衣大叔）",
        "homepage_url": "https://www.douyin.com/user/MS4wLjABAAAAJ3T5moYwIGWeicRl5wBdfosV7R_dCmIbcmAIVZ_3iLK3aLLrOq9pWQDaZBfU0kpQ?from_tab_name=main",
        "query_hint": "site:douyin.com/user 周鸿祎 红衣大叔 抖音",
        "category": "ai_business",
    },
    {
        "platform": "douyin",
        "display_name": "洋过探世界",
        "homepage_url": "https://www.douyin.com/user/MS4wLjABAAAA4_Z4azV9QXsPV42NWF9B9IeFOgYCI9OXrIUeHftx0TwfCQPvKiq9Dz-PxBkhl2LB?from_tab_name=main",
        "query_hint": "site:douyin.com/user 洋过探世界 抖音",
        "category": "content_reference",
    },
    {
        "platform": "douyin",
        "display_name": "小五狼",
        "homepage_url": "https://www.douyin.com/user/MS4wLjABAAAAaEO1djQykbPFCAX_QtSVBmULgfRMW_txc5z-_3FfBMY?from_tab_name=main",
        "query_hint": "site:douyin.com/user 小五狼 抖音",
        "category": "content_reference",
    },
    {
        "platform": "douyin",
        "display_name": "贝乐虎儿歌",
        "homepage_url": "https://www.douyin.com/user/MS4wLjABAAAAoJtQs2kZmNRkpgdJ5bqiGo5Tew1SpfraM4w_E7511HQ?from_tab_name=main",
        "query_hint": "site:douyin.com/user 贝乐虎儿歌 抖音",
        "category": "children_content",
    },
    {
        "platform": "douyin",
        "display_name": "儿歌多多",
        "homepage_url": "https://www.douyin.com/user/MS4wLjABAAAA4DXjHfG0tltAUoX86re-41hAocOY2MguXcrL-ZZDYrU?from_tab_name=main",
        "query_hint": "site:douyin.com/user 儿歌多多 抖音",
        "category": "children_content",
    },
]
